apiVersion: v1
kind: Service
metadata:
  name: docker
  namespace: namespace-workflow-1700121281176
spec:
  type: LoadBalancer
  selector:
    app: docker
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173